name = "posthog-reverse-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "posthog-reverse-proxy-staging"

[env.production]
name = "posthog-reverse-proxy-production"
